/** Initial editorial drafts. After seeding, the workbook is the editable source. */
function evergreenSeedRows_() {
  const shaw = 'https://pdmsview.shawinc.com/USFloors/COREtec/Installation/SPC-Installation-Guidelines-Unbranded-10162018';
  const laminate = 'https://nalfa.com/laminate-flooring-faqs/';
  const ratings = 'https://nalfa.com/wp-content/uploads/2022/11/NALFA-AC-Rating-White-Paper_Final.pdf';
  const water = 'https://nalfa.com/wp-content/uploads/2024/05/NALFA-White-Paper_Laminate-Flooring-Water-Performance_FINAL-4-17-24.pdf';
  const spec = 'https://pdmsview.shawinc.com/spec-viewer/?key=IyElJEc%2BRyMhJSQ%3D&region=EN-US';
  // ID, type, title, explanation, comparison/context, practical takeaway, primary references.
  const topics = [
    ['EDU-01','Educational','Wear layer: 6, 12 or 22 MIL?',
      'The wear layer is the protective layer above a vinyl floor\'s printed design. MIL means thousandths of an inch, not millimeters.',
      '6, 12 and 22 MIL describe wear-layer thickness, not total plank thickness. Traffic, finish and warranty matter too.',
      'Compare the actual product specification and intended use. A larger MIL number is not a promise against every scratch.',spec],
    ['EDU-02','Educational','Does thicker always mean better?',
      'Total thickness combines different layers. A thicker pad is not the same as a thicker core or wear layer.',
      'Check core construction, locking system, finish and permitted use. Thickness alone does not measure all durability.',
      'Compare complete specifications and installation requirements, not just one number.',spec+' '+shaw],
    ['EDU-03','Educational','SPC vs laminate: know the construction',
      'SPC is a rigid mineral-filled vinyl flooring construction. Laminate typically uses a wood-fiber core with a decorative surface.',
      'They have different moisture and installation requirements. Water claims must be checked for the exact model.',
      'Choose for the room, subfloor and product warranty, not the category label alone.',shaw+' '+laminate],
    ['EDU-04','Educational','Waterproof vs water-resistant',
      'Water-performance claims have specific conditions. They do not automatically protect the subfloor, seams, walls or an entire room.',
      'Standing water, leaks and installation details matter. Read the exact product warranty and cleanup instructions.',
      'Address leaks promptly and verify approved room use. Waterproof is not a flood-proof promise.',water+' '+shaw],
    ['EDU-05','Educational','What does attached pad mean?',
      'Attached pad is backing already bonded to the plank. Depending on the product, it can help with sound or underfoot feel.',
      'It does not fix an uneven subfloor. An extra pad or moisture barrier may have separate product-specific requirements.',
      'Follow the exact manufacturer guide before adding any underlayment.',shaw],
    ['EDU-06','Educational','5 mm vs 6.5-7 mm LVP',
      'First confirm whether the published thickness includes attached pad. Compare total thickness and core thickness consistently.',
      'A 5 mm plank and a 6.5-7 mm plank can differ in pad, core, locking system and wear layer.',
      'Ask for wear layer, pad details and permitted use alongside overall thickness.',spec+' '+shaw],
    ['EDU-07','Educational','How much extra flooring should you buy?',
      'Cuts, layout and damaged pieces can increase material needs. The right waste allowance depends on the project.',
      'Straight layouts and complex or diagonal layouts may need different allowances. Check the product guide and installer estimate.',
      'Use the project calculator with an appropriate waste percentage, then round up to whole boxes.',shaw],
    ['EDU-08','Educational','Calculate your flooring square footage',
      'For a rectangular room, multiply length in feet by width in feet. Convert inches to feet before multiplying.',
      'Split an irregular space into rectangles and add their areas. Then account for cutting waste separately.',
      'Measure carefully and confirm your layout. Area, recommended coverage and purchased coverage are different numbers.',shaw],
    ['EDU-09','Educational','What is click-lock flooring?',
      'Click-lock describes interlocking plank joints. Many products use a floating installation, but requirements vary.',
      'Flatness, expansion space and the correct joint technique still matter. Click-lock does not mean every subfloor is suitable.',
      'Use the exact model\'s installation guide. Do not force damaged joints together.',shaw],
    ['EDU-10','Educational','Same thickness, different price?',
      'Two floors with the same overall thickness can have different cores, wear surfaces, finishes and backing.',
      'Brand, design, locking construction, warranty terms and inventory sourcing can also affect price.',
      'Compare specifications and total project cost before deciding which is the better value.',spec],
    ['EDU-11','Educational','What is AC rating on laminate?',
      'AC is an abrasion classification used for laminate. It describes one aspect of tested wear performance.',
      'AC rating does not by itself measure every type of damage or water performance. It is not the vinyl MIL system.',
      'Check intended use, other performance data and warranty as well as the AC rating.',ratings],
    ['EDU-12','Educational','Flooring for pets: what to check',
      'Consider scratch resistance, texture, cleaning guidance and how the product handles spills or accidents.',
      'A thick wear layer alone does not guarantee scratch-proof flooring. Nails, grit and furniture can still damage surfaces.',
      'Use mats and manufacturer-approved care. Compare the exact warranty instead of assuming pet-proof means damage-proof.',laminate+' '+spec],
    ['EDU-13','Educational','Flooring for rental properties',
      'Match flooring to likely traffic, turnover, maintenance and the rooms where it will be used.',
      'Compare repair options, replacement-stock availability and permitted use. The cheapest or thickest choice is not always the best fit.',
      'Budget for complete coverage and future repairs. Confirm suitability with the exact product documentation.',laminate+' '+shaw],
    ['EDU-14','Educational','12 MIL vs 22 MIL: practical differences',
      '22 MIL is a thicker wear layer than 12 MIL. That is a useful specification, not a complete floor-performance score.',
      'Finish, traffic, care and warranty still matter. A larger number is not automatically necessary for every home.',
      'Match the product\'s permitted use to your room and traffic, then compare value.',spec],
    ['EDU-15','Educational','SPC construction explained',
      'A typical SPC plank combines a protective surface, printed design and rigid mineral-filled core. Some include attached backing.',
      'Construction varies by model. Overall thickness can include backing, while wear layer is measured separately.',
      'Read the layer specifications and installation guide for the exact plank you are buying.',shaw+' '+spec],
    ['EDU-16','Educational','What does the wear layer protect?',
      'The wear layer helps protect a vinyl floor\'s decorative image from surface wear during use.',
      'It is not a guarantee against deep scratches, dents, joint damage or problems caused by an unsuitable subfloor.',
      'Pair suitable specifications with correct installation and care. No single layer protects against every problem.',spec+' '+shaw],
    ['EDU-17','Educational','Attached pad vs separate underlayment',
      'Attached pad comes on the plank. Separate underlayment is an additional product beneath the flooring.',
      'Extra cushioning is not always approved and can affect joint performance. Moisture barriers are a separate consideration.',
      'Check your exact floor and subfloor instructions before buying an extra layer.',shaw],
    ['EDU-18','Educational','Inspect discount and overstock flooring',
      'Check the exact model, box coverage, condition, quantity and any lot or shade information before committing.',
      'Inspect plank edges and locking joints. Confirm that there is enough compatible material for your complete project.',
      'Ask about condition and applicable terms. Do not assume more stock will be available later.',shaw+' https://invictahomesupply.com/shop.html'],
    ['EDU-19','Educational','What drives flooring price?',
      'Thickness and wear layer are only part of the picture. Core, finish, pad, locking system and design can differ.',
      'Inventory sourcing and availability also influence resale pricing. A price comparison should use like-for-like specifications.',
      'Compare full product details, condition and whole-box project cost.',spec+' https://invictahomesupply.com/shop.html'],
    ['EDU-20','Educational','How many boxes should you buy?',
      'Recommended square footage equals measured area plus your chosen waste allowance.',
      'Divide recommended coverage by square feet per box and round up. Whole boxes determine actual purchased coverage.',
      'For 300 sq ft with 10% waste and 20 sq ft per box: 330 recommended, 17 boxes, 340 sq ft purchased.',shaw],
    ['CMP-01','Comparison','5 mm / 12 MIL vs 7 mm / 22 MIL',
      'These examples describe two different measurements: overall plank thickness and wear-layer thickness.',
      'The second example has larger numbers, but compare core, pad, finish, room suitability and warranty before choosing.',
      'Ask what each thickness includes. Choose for your use case rather than treating one option as universally better.',spec+' '+shaw],
    ['CMP-02','Comparison','SPC or laminate for your room?',
      'SPC uses a rigid mineral-filled vinyl core. Laminate typically uses a wood-fiber core with a protected decorative surface.',
      'Compare moisture claims, surface performance, feel, installation requirements and approved room use for each model.',
      'There is no universal winner. Match the exact product to the space and maintenance needs.',laminate+' '+shaw],
    ['CMP-03','Comparison','12 MIL or 22 MIL?',
      '12 MIL and 22 MIL describe vinyl wear-layer thickness. Neither tells you the entire floor construction.',
      'More wear material can be useful, but finish quality, traffic and permitted use also influence the decision.',
      'Compare the warranty and specifications. Do not assume 22 MIL is necessary for every household.',spec],
    ['CMP-04','Comparison','Attached pad or no attached pad?',
      'With attached pad, backing is already part of the plank. Without it, underlayment needs depend on the specific system.',
      'Compare approved materials and full installation cost. Do not automatically add a second soft pad.',
      'Follow the model-specific guide, including subfloor and moisture-barrier requirements.',shaw],
    ['CMP-05','Comparison','Budget vs premium: compare construction',
      'Budget and premium are price labels, not standardized floor-performance grades.',
      'Compare wear surface, core, locking joints, backing, finish and applicable warranty. Similar-looking planks may differ.',
      'Choose a suitable complete specification and project cost, not a label alone.',spec+' '+laminate],
    ['CMP-06','Comparison','Rentals vs owner-occupied homes',
      'Rental projects often emphasize turnover, cleaning and repair practicality. Homeowners may prioritize feel, style and long-term use.',
      'Both need room-appropriate performance and enough compatible stock. Neither has a single required thickness or wear layer.',
      'Write down traffic, moisture exposure, care and repair needs, then compare suitable options.',laminate+' '+shaw],
    ['TIP-01','Tip','Measure twice before choosing boxes',
      'Write down each room\'s length and width, including units. Separate irregular spaces into smaller areas.',
      'Keep base area, waste allowance and whole-box coverage distinct. Confirm your box coverage before ordering.',
      'Bring your measurements when asking about inventory. We can help compare the posted product details.',shaw],
    ['TIP-02','Tip','Keep a small repair reserve',
      'Consider whether spare matching planks are useful for future repairs after completing your project.',
      'Keep the model and lot details. Overstock inventory may not return, so later replacement stock is not guaranteed.',
      'Plan the reserve intentionally and store it according to the manufacturer\'s instructions.',shaw],
    ['BRAND-01','Brand','Compare flooring with confidence',
      'Start with your room, measured area and intended use. Then compare complete product specifications.',
      'Invicta Home Supply lists product details and pricing to help you compare available options.',
      'Need help comparing flooring options? Message Invicta Home Supply in McKinney, TX.', 'https://invictahomesupply.com/shop.html'],
    ['BRAND-02','Brand','Plan your local flooring pickup',
      'Confirm current stock, box coverage and project quantity before planning your pickup.',
      'Flooring is currently available for local pickup in McKinney, TX. We do not currently ship individual flooring orders.',
      'Local delivery is available for an additional fee. Contact us for a delivery quote.', 'https://invictahomesupply.com/shop.html']
  ];
  return topics.map(function(topic) {
    const caption = topic[2]+'\n\n'+topic[3]+' '+topic[4]+'\n\n'+topic[5]+'\n\nNeed help comparing flooring options? Message Invicta Home Supply.';
    const row = [topic[0],topic[1],topic[2],caption,topic[2],topic[3],topic[4],topic[5],'Enabled',120,topic[6]];
    evergreenContent_(row);return row;
  });
}
